id: P000397
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:37:50.745429
source_metadata:
  id: bdr:W00KG09694
  title: གྲུབ་མཐའི་རྣམ་བཤད་ཀུན་བཟང་ཞིང་གི་ཉི་མ་
  author: ''
  volumes:
    b89d1201366d42feb94fdd28d2a1fd23:
      image_group_id: I00KG09712
      title: Volume 1 of grub mtha'i rnam bshad kun bzang zhing gi nyi ma
      volume_number: 1
      total_pages: 978
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
