id: I0BB3A86D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T22:16:18+00:00'
last_modified: '2022-06-10T05:09:13.247226+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09694
  title: གྲུབ་མཐའི་རྣམ་བཤད་ཀུན་བཟང་ཞིང་གི་ཉི་མ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FF5B:
      image_group_id: I00KG09712
      title: Volume 1 of grub mtha'i rnam bshad kun bzang zhing gi nyi ma
      total_pages: 978
      order: 1
      base_file: FF5B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
